version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.6-stretch
    steps:
      - checkout
      - run: python --version
      - run: sudo pip install requests
      - run: sudo apt-get update && sudo apt-get -y install python3-sleekxmpp
      - run: python test.py "${HELLO_SECRET}"
