version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.6-stretch
    steps:
      - checkout
      - run: python --version
      - run: sudo pip install sleekxmpp
      - run: python test.py "${HELLO_SECRET}"
